{
 "title": "top tags over time filtered by taxonomy",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "taxonomy",
    "label": "taxonomies",
    "query": "select * from taxonomy where \"classification.taxonomy\" != 'test'"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "# Classification.* over time\n\nThe following graph shows the 3 classification.* fields over time: \n\n  * \"classification.taxonomy\", \n  * \"classification.type\", \n  * \"classification.identifier\". \n\nSelect the taxonomy on top to filter and drill down to \"type\" and \"identifier\""
  },
  {
   "title": "Taxonomy '$taxonomy' over time (log scale!)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(\"count\") as x,\n  \"classification.taxonomy\"\nFROM agg_ndim_day_all_tags\nWHERE\n  $__timeFilter(date) AND\n  \"classification.taxonomy\" in ( $taxonomy)  AND\n  \"classification.taxonomy\" != 'some random string LTHADGDHTGTGYjhgsytsath'    -- grafana workaround\nGROUP BY 1, 3\n-- HAVING max(\"count\") > 500\nORDER BY 1,3"
    }
   ]
  },
  {
   "title": "Type over time (log scale!) / $taxonomy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(\"count\") as x,\n  \"classification.type\"\nFROM agg_ndim_day_all_tags\nWHERE\n  $__timeFilter(date) AND\n  \"classification.taxonomy\" in ( $taxonomy)  AND\n  \"classification.type\" != 'some random string LTHADGDHTGTGYjhgsytsath'    -- grafana workaround\nGROUP BY 1, 3\n-- HAVING max(\"count\") > 500\nORDER BY 1,3"
    }
   ]
  },
  {
   "title": "Identifier over time / $taxonomy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(\"count\") as x,\n  \"classification.identifier\"\nFROM agg_ndim_day_all_tags\nWHERE\n  $__timeFilter(date) AND\n  \"classification.taxonomy\" in ( $taxonomy)  AND\n  \"classification.identifier\" != 'some random string LTHADGDHTGTGYjhgsytsath'    -- grafana workaround\nGROUP BY 1, 3\n-- HAVING max(\"count\") > 500\nORDER BY 1,3"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "content": "# Top 10 protocols over time\n\nThe following graph shows the top 10 \"protocol.application\"s over time. Select the taxonomy on top to filter."
  },
  {
   "title": "protocol.application over time / $taxonomy",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(\"count\") as x,\n  \"protocol.application\"\nFROM agg_ndim_day_all_tags\nWHERE\n  $__timeFilter(date) AND\n  \"classification.taxonomy\" in ( $taxonomy)  AND\n  \"protocol.application\" in ('https', 'rdp', 'tftp', 'cwmp', 'telnet', 'ntp', 'dns', 'ssdp', 'netbios-name', 'snmp') AND\n  \"classification.taxonomy\" != 'some random string LTHADGDHTGTGYjhgsytsath' and   -- grafana workaround\n  \"protocol.application\" != 'some random string ajhksjgklasjhga'   -- grafana workaround \nGROUP BY 1, \"protocol.application\"\n-- HAVING max(\"count\") > 500\nORDER BY 1,3"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
   "content": "# Data feeds over time\n\nThe following graphs shows the all \"feed.name\" and \"feed.provider\" over time. Select the taxonomy on top to filter.\nFeed.provider shows which data feed gives us how much data (rows)."
  },
  {
   "title": "feed.name over time / $taxonomy",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(\"count\") as x,\n  \"feed.name\"\nFROM agg_ndim_day_all_tags\nWHERE\n  $__timeFilter(date) AND\n  \"classification.taxonomy\" in ( $taxonomy)  AND\n  \"protocol.application\" in ('https', 'rdp', 'tftp', 'cwmp', 'telnet', 'ntp', 'dns', 'ssdp', 'netbios-name', 'snmp') AND\n  \"classification.taxonomy\" != 'some random string LTHADGDHTGTGYjhgsytsath'    -- grafana workaround\nGROUP BY 1, \"feed.name\"\n-- HAVING max(\"count\") > 500\nORDER BY 1,3"
    }
   ]
  },
  {
   "title": "feed.provider over time / $taxonomy (log scale!)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(\"count\") as x,\n  \"feed.provider\"\nFROM agg_ndim_day_all_tags\nWHERE\n  $__timeFilter(date) AND\n  \"classification.taxonomy\" in ( $taxonomy)  AND\n  -- \"protocol.application\" in ('https', 'rdp', 'tftp', 'cwmp', 'telnet', 'ntp', 'dns', 'ssdp', 'netbios-name', 'snmp') AND\n  \"classification.taxonomy\" != 'some random string LTHADGDHTGTGYjhgsytsath'    -- grafana workaround\nGROUP BY 1, \"feed.provider\"\n-- HAVING max(\"count\") > 500\nORDER BY 1,3"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 73 },
   "content": "# Malware over time\n\nThe following graphs shows the all \"malware.name\" stats over time. Please note that this only makes sense for the taxonomy 'malicious code'. "
  },
  {
   "title": "Malware over time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(\"count\") as x,\n  \"malware.name\"\nFROM agg_ndim_day_all_tags\nWHERE\n  $__timeFilter(date) AND\n  \"classification.taxonomy\" = 'malicious code' AND\n  \"classification.taxonomy\" != 'some random string LTHADGDHTGTGYjhgsytsath' and    -- grafana workaround\n  \"malware.name\" != 'some random string LTHADGDHTGTGYjhgsytsath'\nGROUP BY 1, \"malware.name\"\n-- HAVING max(\"count\") > 500\nORDER BY 1,3"
    }
   ]
  },
  {
   "title": "Countries over time / $taxonomy",
   "type": "graph",
   "description": "This lists the number of distinct IP addresses we see for each country over time. Of course, a focus is on Austria. So the stats are pretty clearly dominated by \"AT\". But we also (by accident) get data from other countries. Sometimes, \"AT\" and \"AU\" (Australia) get confused.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(\"count\") as x,\n  \"source.geolocation.cc\"\nFROM agg_ndim_day_all_tags\nWHERE\n  $__timeFilter(date) AND\n  \"classification.taxonomy\" in ( $taxonomy ) AND\n  \"classification.taxonomy\" != 'some random string LTHADGDHTGTGYjhgsytsath' and    -- grafana workaround\n  \"source.geolocation.cc\" != 'some random string LTHADGDHTGTGYjhgsytsath'\nGROUP BY 1, 3\n-- HAVING max(\"count\") > 500\nORDER BY 1,3"
    }
   ]
  }
 ]
}